import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { NetworkOnly } from 'workbox-strategies';

// Precache all files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache HTML files (your main app files)
registerRoute(
  ({ request }) => request.destination === 'document',
  new StaleWhileRevalidate({
    cacheName: 'html-cache',
  })
);

// Cache CSS and JavaScript files
registerRoute(
  ({ request }) =>
    request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'assets-cache',
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          // Asegúrate de que la respuesta sea válida
          if (response && response.status === 200) {
            return response;
          }
          return null;
        },
      },
    ],
  })
);

// No cachear videos de YouTube, pero mostrar un fallback si está offline
registerRoute(
  ({ request }) => request.destination === 'video' && request.url.includes('youtube.com'),
  new NetworkOnly({
    cacheName: 'video-external-cache',
  })
);

// Mostrar un fallback cuando no hay conexión
self.addEventListener('fetch', (event) => {
  if (event.request.destination === 'video' && event.request.url.includes('youtube.com')) {
    event.respondWith(
      fetch(event.request).catch(() => {
        return new Response(
          'Video no disponible sin conexión. Por favor, conéctese a Internet para ver este contenido.',
          { headers: { 'Content-Type': 'text/plain' } }
        );
      })
    );
  }
});

// Cache other requests (e.g., API calls, etc.)
registerRoute(
  /.*/,
  new StaleWhileRevalidate({
    cacheName: 'all-resources-cache',
  })
);
