// service-worker.js

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

// Precache all files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache HTML files (your main app files)
registerRoute(
  ({ request }) => request.destination === 'document',
  new StaleWhileRevalidate({
    cacheName: 'html-cache',
  })
);

// Cache CSS and JavaScript files
registerRoute(
  ({ request }) =>
    request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'assets-cache',
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          // Asegúrate de que la respuesta sea válida
          if (response && response.status === 200) {
            return response;
          }
          return null;
        },
      },
    ],
  })
);

// Cache videos
registerRoute(
  ({ request }) => request.destination === 'video',
  new CacheFirst({
    cacheName: 'video-cache',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          // Asegúrate de que la respuesta sea válida
          if (response && response.status === 200) {
            return response;
          }
          return null;
        },
      },
    ],
  })
);

// Cache other requests (e.g., API calls, etc.)
registerRoute(
  /.*/,
  new StaleWhileRevalidate({
    cacheName: 'all-resources-cache',
  })
);
